lib/lfc_web/router.ex
defmodule LfcWeb.Router do
  use LfcWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LfcWeb.Auth, accounts: Lfc.Accounts

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", DashboardController, only: [:index]
    resources "/users", UserController, except: [:delete]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/password", PasswordController, except: [:delete, :show, :index]
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    get "/sign-up", FighterController, :new
    get "/thank-you", FighterController, :thank_you
    resources "/sign-up", FighterController, only: [:create]
    resources "/contacts", ContactController, only: [:create]
  end

  # authed routes
  scope "/", LfcWeb do
    pipe_through [:browser, :authenticate]

    resources "/dashboard", AdminDashboardController, only: [:index]
    resources "/events", EventController, only: [:create, :delete]
    get "/fighter-csv", CsvController, :export_fighters
  end

  # Other scopes may use custom stacks.
  # scope "/api", LfcWeb do
  #   pipe_through :api
  # end
end

lib/lfc_web/views/layout_view.ex
defmodule LfcWeb.LayoutView do
  use LfcWeb, :view
end

lib/lfc_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fight Club London</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->

  </head>
  <body class="l-bg-dark-grey k-indigo mb0 roboto">
    <header>
      <nav role="navigation" class="flex k-h6 bb l-bg-dark-grey relative bn">
          <div class="app-container w-100 h4 mt2 center l-bg-dark-grey">
              <a href="/" class="h4 ml0-ns">
                <div class="h3 dt pb3 dib fl mr4">
                  <p class="dib f3 pl1 fw4 white ma0 dtc v-mid l-pt-1-8">Fight Club London</p>
                </div>
              </a>
              <%= if @current_user do %>
                <div class="white fr k-mt3-5 fw4">
                  <%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete", class: "back-button hover-purple link white ml4-ns ml3 mv4 mb0-ns outline-0" %>
                </div>
              <% end %>
          </div>
      </nav>
    </header>
    <p class="absolute w-100 tc alert pa3 br2 mt0 white l-bg-pink" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="absolute w-100 tc alert pa3 br2 mt0 mb4 white l-bg-pink" role="alert"><%= get_flash(@conn, :error) %></p>
    <article class="k-mt9 center h-100 bg-white relative-ns pb7-ns pb6 min-vh-100-ns relative">
      <main role="main" class="h-100 bg-white app-container center relative">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </article> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/lfc_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fight Club London</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->

  </head>
  <body class="k-bg-lighter-grey k-indigo mb0">
    <header>
      <nav role="navigation" class="flex k-h8 bb bg-white l-dark-grey fixed w-100 z-999 bn shadow-1">
          <div class="app-container w-100 h4 mt2 center l-dark-grey">
              <a href="/" class="h4 ml0-ns">
                <div class="h3 dt pb3 dib fl mr4">
                  <p class="dib f3 pl1 fw4 l-dark-grey ma0 dtc v-mid">
                    <img src="/images/logo-main.png"  class="l-w7"/>
                  </p>
                </div>
              </a>
              <div class="fr pt-1-5 mt2 nav-logo white pr2 pointer:hover">
                <img src="/images/menu.svg" class="w3 ml4 pointer pt3" id="nav-menu-button" />
              </div>
              <%= if @current_user do %>
                <div class="l-dark-grey fr mt4 pt3 fw4 fjalla">
                  <%= link "Admin", to: admin_dashboard_path(@conn, :index), class: "pt3 back-button hover-purple link l-dark-grey ml4-ns ml3 mv4 mb0-ns outline-0" %>
                </div>
              <% else %>
                <div class="black fr mt4 f4 fw4 l-destroy pt3">
                  <%= link "Sign up", to: fighter_path(@conn, :new), class: "back-button hover-purple link black mv4 mb0-ns outline-0" %>
                </div>
              <% end %>
          </div>
      </nav>
      <%= if get_flash(@conn, :error) do %>
        <p class="fixed l-mt6 z-999 w-100 error-message fjalla white l-bg-main-red tc pt3 pb3" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <%= if get_flash(@conn, :info) do %>
        <p class="fixed l-mt6 z-999 w-100 error-message fjalla white l-bg-main-red tc pt3 pb3" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <div class="tc bg-white pierlight pt2 pb2 mt-0-3 bt2-grey dn fixed l-mt6 z-999 fjalla right-0 w-50 w-20-ns nav-borders" id="nav-menu">
        <div class="tc m-auto bb1-grey pb3 pt3">
          <a href="#who-are-we" id="who-are-we-link" class="link no-underline l-dark-grey">
            <div>who are we?</div>
          </a>
        </div>
        <div class="tc m-auto bb1-grey pb3 pt3">
          <a href="#how-it-works" id="how-it-works-link" class="link no-underline l-dark-grey">
            <div>how it works</div>
          </a>
        </div>
        <div class="tc m-auto bb1-grey pb3 pt3">
          <a href="#where-is-it" id="where-is-it-link" class="link no-underline l-dark-grey">
            <div>where is it?</div>
          </a>
        </div>
        <div class="tc m-auto bb1-grey pb3 pt3">
          <a href="#testimonials" id="testimonials-link" class="link no-underline l-dark-grey">
            <div>testimonials</div>
          </a>
        </div>
        <div class="tc m-auto bb1-grey pb3 pt3">
          <a href="#contact" id="contact-link" class="link no-underline l-dark-grey">
            <div>contact</div>
          </a>
        </div>
      </div>
    </header>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 dark-grey bg-light-green b--dark-green" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 mb4 white bg-light-red b--red" role="alert"><%= get_flash(@conn, :error) %></p>
    <div class="center h-100 bg-white relative-ns min-vh-100-ns relative">
      <main role="main" class="h-100 bg-white center relative l-minh-100vh">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->

    <!-- FOOTER -->
    <footer class="relative l-bg-dark-grey l-footer-grey white tc">
      <div class="w-100 h6-ns h-100 bottom-0 app-container center">
        <div class="mt0 pt4 pb4 b--black-20 bt">
          <article class="cf mt0">
            <div class="w-100 mb0-ns">
              <div class="h3 dib pt1">
                <img src="/images/logo-main-grey.png"  class="l-w6"/>
              </div>
              <div class="pt2">
                <a href="https://www.facebook.com/BeatsBoxing-London-1440831619515385/" class="no-underline">
                  <img src="/images/facebook.svg" class="w2 dib ml1 mr1" />
                </a>
                <img src="/images/twitter.svg" class="w2 dib ml1 mr1" />
                <img src="/images/instagram.svg" class="w2 dib ml1 mr1" />
                <div class="pt2">
                  <div class="dib">© 2018 Fight Club Events Ltd</div>
                </div>
              </div>
            </div>
          </article>
          </div>
      </div>
    </footer>
    <script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 51.4621976, lng: -0.1211838},
      zoom: 14,
      styles: [
        {
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#f5f5f5"
            }
          ]
        },
        {
          "elementType": "labels.icon",
          "stylers": [
            {
              "visibility": "off"
            }
          ]
        },
        {
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#616161"
            }
          ]
        },
        {
          "elementType": "labels.text.stroke",
          "stylers": [
            {
              "color": "#f5f5f5"
            }
          ]
        },
        {
          "featureType": "administrative.land_parcel",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#bdbdbd"
            }
          ]
        },
        {
          "featureType": "poi",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#eeeeee"
            }
          ]
        },
        {
          "featureType": "poi",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#757575"
            }
          ]
        },
        {
          "featureType": "poi.business",
          "stylers": [
            {
              "visibility": "off"
            }
          ]
        },
        {
          "featureType": "poi.park",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#e5e5e5"
            }
          ]
        },
        {
          "featureType": "poi.park",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#9e9e9e"
            }
          ]
        },
        {
          "featureType": "road",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#ffffff"
            }
          ]
        },
        {
          "featureType": "road",
          "elementType": "labels.icon",
          "stylers": [
            {
              "visibility": "off"
            }
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#757575"
            }
          ]
        },
        {
          "featureType": "road.highway",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#dadada"
            }
          ]
        },
        {
          "featureType": "road.highway",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#616161"
            }
          ]
        },
        {
          "featureType": "road.local",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#9e9e9e"
            }
          ]
        },
        {
          "featureType": "transit",
          "stylers": [
            {
              "visibility": "off"
            }
          ]
        },
        {
          "featureType": "transit.line",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#e5e5e5"
            }
          ]
        },
        {
          "featureType": "transit.station",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#eeeeee"
            }
          ]
        },
        {
          "featureType": "water",
          "elementType": "geometry",
          "stylers": [
            {
              "color": "#c9c9c9"
            }
          ]
        },
        {
          "featureType": "water",
          "elementType": "labels.text.fill",
          "stylers": [
            {
              "color": "#9e9e9e"
            }
          ]
        }
      ]
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDuipT1y6uLyX3-UjGuNOV5OYqMitN3l2w&callback=initMap"
async defer></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("js/app").App.navListeners()</script>
  </body>
</html>

lib/lfc_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/lfc_web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>

lib/lfc_web/templates/layout/pre_login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fight Club London</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->

  </head>

  <body class="bg-white k-indigo">

      <p class="alert pa4 br2 mb4 alert dark-grey bg-light-green b--dark-green" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert pa4 br2 mb4 white bg-light-red b--red" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main" class="bg-near-white">
        <%= render @view_module, @view_template, assigns %>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/lfc_web/templates/layout/sign_up.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fight Club London</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css"/>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="icon" href="/images/favicon-16.png" sizes="16x16" type="image/png">
    <link rel="icon" href="/images/favicon-32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/images/favicon-64.png" sizes="64x64" type="image/png">
    <!--[if IE]><link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon" /><![endif]--><!-- Internet Explorer-->

  </head>
  <body class="k-bg-lighter-grey k-indigo mb0">
    <header>
      <nav role="navigation" class="flex k-h8 bb bg-white l-dark-grey fixed w-100 z-999 bn shadow-1">
          <div class="app-container w-100 h4 mt2 center l-dark-grey">
              <a href="/" class="h4 ml0-ns">
                <div class="h3 dt pb3 dib fl mr4">
                  <p class="dib f3 pl1 fw4 l-dark-grey ma0 dtc v-mid">
                    <img src="/images/logo-main.png"  class="l-w7"/>
                  </p>
                </div>
              </a>
              <div class="black fr mt4 fw4 l-destroy pt3 ml3">
                <%= link "Home", to: dashboard_path(@conn, :index), class: "back-button hover-purple link black mv4 mb0-ns outline-0" %>
              </div>
              <%= if @current_user do %>
                <div class="l-dark-grey fr mt4 pt3 fw4 fjalla">
                  <%= link "Admin", to: admin_dashboard_path(@conn, :index), class: "back-button hover-purple link l-dark-grey ml4-ns ml3 mv4 mb0-ns outline-0" %>
                </div>
              <% end %>
          </div>
      </nav>
    </header>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 dark-grey bg-light-green b--dark-green" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="absolute w-100 tc alert pa1-5 br2 mt0 mb4 white bg-light-red b--red" role="alert"><%= get_flash(@conn, :error) %></p>
    <div class="center h-100 bg-white relative-ns min-vh-100-ns relative">
      <main role="main" class="h-100 bg-white center relative l-minh-100vh">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->

    <!-- FOOTER -->
    <footer class="relative l-bg-dark-grey l-footer-grey white tc">
      <div class="w-100 h6-ns h-100 bottom-0 app-container center">
        <div class="mt0 pt4 pb4 b--black-20 bt">
          <article class="cf mt0">
            <div class="w-100 mb0-ns">
              <div class="h3 dib pt1">
                <img src="/images/logo-main-grey.png"  class="l-w6"/>
              </div>
              <div class="pt2">
                <a href="https://www.facebook.com/BeatsBoxing-London-1440831619515385/" class="no-underline">
                  <img src="/images/facebook.svg" class="w2 dib ml1 mr1" />
                </a>
                <img src="/images/twitter.svg" class="w2 dib ml1 mr1" />
                <img src="/images/instagram.svg" class="w2 dib ml1 mr1" />
                <div class="pt2">
                  <div class="dib">© 2018 Fight Club Events Ltd</div>
                </div>
              </div>
            </div>
          </article>
          </div>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>