lib/lfc_web/router.ex
defmodule LfcWeb.Router do
  use LfcWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LfcWeb.Auth, accounts: Lfc.Accounts

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", DashboardController, only: [:index]
    resources "/users", UserController, except: [:delete]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/password", PasswordController, except: [:delete, :show, :index]
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    get "/sign-up", FighterController, :new
    get "/thank-you", FighterController, :thank_you
    resources "/sign-up", FighterController, only: [:create]
    resources "/contacts", ContactController, only: [:create]
  end

  # authed routes
  scope "/", LfcWeb do
    pipe_through [:browser, :authenticate]

    resources "/dashboard", AdminDashboardController, only: [:index]
    resources "/events", EventController, only: [:create, :delete]
    get "/fighter-csv", CsvController, :export_fighters
  end

  # Other scopes may use custom stacks.
  # scope "/api", LfcWeb do
  #   pipe_through :api
  # end
end

lib/lfc_web/controllers/dashboard_controller.ex
defmodule LfcWeb.DashboardController do
  @moduledoc """
  Dashboard Controller
  """
  use LfcWeb, :controller
  alias Lfc.Main
  alias Lfc.Main.Contact

  def index(conn, _params) do
    events = Main.list_events()
    changeset = Contact.changeset(%Contact{})
    render conn, "index.html", events: events, changeset: changeset
  end

end

lib/lfc_web/views/dashboard_view.ex
defmodule LfcWeb.DashboardView do
  use LfcWeb, :view
end

lib/lfc_web/templates/dashboard/index.html.eex
<%
  future_events = future_events(@events)
  next_event =
    case length(future_events) > 0 do
      true -> hd(future_events).date
      false -> nil
    end
%>
<div class="pt5">
  <div class="relative hero-container">
    <div class="l-m">
      <video autoplay loop id="myVideo">
        <source src="/images/video-main.mp4" type="video/mp4">
      </video>
    </div>
    <div class="tc l-destroy white absolute timer-container">
      <%= if next_event do %>
      <div class="pt3 f1 f2-ns">LONDON</div>
      <div class="l-f1 pt3">WHITE COLLAR BOXING</div>
      <div class="pt3 ttu">Countdown to next event</div>
        <div class="dib mt4 mb4 l-minw-60">
          <div class="dib f1-ns f2" id="days-d">00</div>
          <div class="f6" id="days-text-d">days</div>
        </div>
        <div class="dib f1-ns f6 clock-separator">:</div>
        <div class="dib mt4 mb4 l-minw-60">
          <div class="dib f1-ns f2" id="hours-d">00</div>
          <div class="f6" id="hours-text-d">hours</div>
        </div>
        <div class="dib f1-ns f6 clock-separator">:</div>
        <div class="dib mt4 mb4 l-minw-60">
          <div class="dib f1-ns f2" id="minutes-d">00</div>
          <div class="f6" id="minutes-text-d">minutes</div>
        </div>
        <div class="dib f1-ns f6 clock-separator">:</div>
        <div class="dib mt4 mb4 l-minw-60">
          <div class="dib f1-ns f2" id="seconds-d">00</div>
          <div class="f6" id="seconds-text-d">secs</div>
        </div>
        <div><%= format_long_date(next_event) %></div>
      <% else %>
        <div class="pt3 f3 f2-ns">LONDON</div>
        <div class="pt3 f3 f1-ns">WHITE COLLAR BOXING</div>
        <div class="f3 pt3 ttu">Next event coming soon!</div>
      <% end %>
      <%= link to: fighter_path(@conn, :new), class: "link no-underline white" do %>
        <div class="ba dib pa3 knockout l-pt3-5 f1 mt4 br2 l-main-red hover-red l-button pl4 pr4 bw2 ttu">Sign up now</div>
      <% end %>
    </div>
  </div>
  <div>
    <div class="pa3 pt4 pb4 l-bg-main-red white tc who-are-we pb5">
      <div class="relative">
        <div class="l-destroy f2 br2 box-shadow-grey pa2 dib ttu"><span class="anchor-span" id="who-are-we"></span>Who are we?</div>
        <div class="pt4">
          <div class="tl">
            <div class="w-80-ns dib pa3 tl f1 l-destroy pt4 hideme ttu">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
              ut labore et dolore magna aliqua.
            </div>
          </div>
          <div class="tl pb5">
            <div class="w-80-ns dib pa3 tl f2 pt2 hidemenext fjalla">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
              ut labore et dolore magna aliqua.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pa3 pt4 pb4 l-bg-grey black tc how-it-works">
    <div class="relative max-w40 m-auto">
      <div class="l-destroy f2 black br2 pa2 ttu"><span class="anchor-span" id="how-it-works"></span>How it works</div>
      <div class="tc m-auto pt5 pb4">
        <%= component "how_it_works_tile.html",
        title: "Sign up",
        subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
        ut labore et dolore magna aliqua.",
        image: "1"
        %>
        <%= component "how_it_works_tile.html",
        title: "Train",
        subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
        ut labore et dolore magna aliqua.",
        image: "2"
        %>
        <%= component "how_it_works_tile.html",
        title: "Fight",
        subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
        ut labore et dolore magna aliqua.",
        image: "3"
        %>
      </div>
      <div>
        <video controls id="myOtherVideo" class=" w-100 w-60-ns m-auto">
          <source src="/images/video-main.mp4" type="video/mp4">
        </video>
      </div>
      <div class="pb4">
        <%= link to: fighter_path(@conn, :new), class: "link no-underline white" do %>
          <div class="ba dib pa3 knockout l-pt3-5 f1 mt4 br2 l-main-red hover-white l-button pl4 pr4 bw2 ttu">Sign up now</div>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <div class="pa3 pt4 pb4 bg-white tc">
      <div class="relative">
        <div class="l-destroy f2 l-main-blue br2 box-shadow-grey pa2 dib pb4 ttu"><span class="anchor-span" id="where-is-it"></span>Where is it?</div>
        <div id="map"></div>
      </div>
    </div>
  </div>
  <div>
    <div class="pa3 pt4 pb4 white tc testimonials">
      <div class="relative">
        <div class="l-destroy f2 br2 box-shadow-grey pa2 dib ttu"><span class="anchor-span" id="testimonials"></span>Testimonials</div>
        <div class="pb4 pt4">
          <div class="tc m-auto w-90-ns d-grid">
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
              ut labore et dolore magna aliqua." %>
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet." %>
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
              ut labore." %>
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor." %>
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
              ut labore et dolore magna aliqua." %>
            <%= component "testimonial_tile.html",
              person: "John Smith",
              quote: "Lorem ipsum dolor sit amet, consectetur adipiscing." %>
          </div>
          <div class="pb4">
            <%= link to: fighter_path(@conn, :new), class: "link no-underline white" do %>
              <div class="ba dib pa3 knockout white l-pt3-5 f1 mt4 br2 l-b--main-red l-bg-main-red hover-red l-button pl4 pr4 bw2 ttu">Sign up now</div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="pa3 pt4 pb4 bg-white tc">
      <div class="relative">
        <div class="l-destroy f2 l-main-blue br2 box-shadow-grey pa2 dib ttu"><span class="anchor-span" id="contact"></span>Contact</div>
        <div class="fjalla f3 l-main-blue pt4 pb4">Please get in touch if you have any questions or want to find out more and we'll get back to you</div>
        <div class="pt4">
          <%= form_for @changeset, contact_path(@conn, :create), fn f -> %>
            <div class="w-80-ns m-auto">
              <div class="w-100 l-w-49-ns dib fl">
                <%= component "input.html",
                form: f,
                atom: :name,
                label: "Name*",
                placeholder: ""
                %>
                <%= component "input.html",
                form: f,
                atom: :email,
                label: "Email*",
                placeholder: ""
                %>
                <%= component "input.html",
                form: f,
                atom: :mobile_number,
                label: "Mobile number*",
                placeholder: ""
                %>
              </div>
              <div class="w-100 l-w-49-ns dib fr">
                <%= component "textarea.html",
                form: f,
                atom: :message,
                label: "Message*",
                placeholder: "",
                class: "l-minh-16"
                %>
              </div>
              <div class="w-50-ns m-auto pb2">
                <%= component "submit_button.html", title: "SEND" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script>require("js/app").App.fadeIn()</script>
<%= if next_event do %>
  <script>require("js/app").App.timerListeners(<%= next_event.day %>, <%= next_event.month %>, <%= next_event.year %>, "-d")</script>
<% end %>