lib/lfc_web/router.ex
defmodule LfcWeb.Router do
  use LfcWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LfcWeb.Auth, accounts: Lfc.Accounts

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", DashboardController, only: [:index]
    resources "/users", UserController, except: [:delete]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/password", PasswordController, except: [:delete, :show, :index]
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    get "/sign-up", FighterController, :new
    get "/thank-you", FighterController, :thank_you
    resources "/sign-up", FighterController, only: [:create]
    resources "/contacts", ContactController, only: [:create]
  end

  # authed routes
  scope "/", LfcWeb do
    pipe_through [:browser, :authenticate]

    resources "/dashboard", AdminDashboardController, only: [:index]
    resources "/events", EventController, only: [:create, :delete]
    get "/fighter-csv", CsvController, :export_fighters
  end

  # Other scopes may use custom stacks.
  # scope "/api", LfcWeb do
  #   pipe_through :api
  # end
end

lib/lfc_web/controllers/admin_dashboard_controller.ex
defmodule LfcWeb.AdminDashboardController do
  use LfcWeb, :controller

  alias LfcWeb.LayoutView
  alias Lfc.Main
  alias Lfc.Main.{Event}

  def index(conn, _params) do
    events = Main.list_events()
    fighters = Main.list_fighters()
    contacts = Main.list_contacts()
    changeset = Main.change_event(%Event{})
    render(conn,
    "index.html",
    layout: {LayoutView, "admin.html"},
    fighters: fighters,
    contacts: contacts,
    events: events,
    changeset: changeset)
  end
end

lib/lfc_web/views/admin_dashboard_view.ex
defmodule LfcWeb.AdminDashboardView do
  use LfcWeb, :view
end

lib/lfc_web/templates/admin_dashboard/index.html.eex
<%
  total_fighters = length(@fighters)
  new_this_month = this_month(@fighters)
  future_events = future_events(@events)
  next_event =
    case length(future_events) > 0 do
      true -> hd(future_events).date
      false -> nil
    end
%>
<h1 class="white top--header absolute mb0 fw1">Dashboard</h1>
<div class="l-minh-100vh l-dark-grey pt4">
  <div>
    <div>Recent activity</div>
    <div class="pt3 pb4 overflow-scroll l-s">
      <table class="w-100 data-table">
        <tr>
          <td class="tc pt5 pb5 w-50 data-td">
            <div class="f1"><%= total_fighters %></div>
            <div class="l-lighter-grey">Total fighters</div>
          </td>
        </tr>
        <tr>
          <td class="tc pt5 pb5 w-50 data-td">
            <div class="f1"><%= new_this_month %></div>
            <div class="l-lighter-grey">New this month</div>
          </td>
        </tr>
        <tr>
          <td class="tc pt4 pb4 w-50 data-td overflow-scroll nowrap">
            <div>
              <%= form_for @changeset, event_path(@conn, :create), fn f -> %>
                <%= component "date.html",
                    atom: :date,
                    form: f,
                    label: "" %>
                <div class="tc">
                  <div>
                    <%= submit "Create", class: "white l-b--blue l-bg-blue k-min-h-4-7 ttu pa2 pl4 pr4 f3 br2 lato mt3 no-outline-focus button-active" %>
                  </div>
                </div>
              <% end %>
              <div class="l-lighter-grey pt3">New event</div>
            </div>
          </td>
        </tr>
        <tr>
          <td class="tc pt4 pb4 w-50 data-td">
            <%= if next_event do %>
              <div class="l-mb--1 pt2"><%= format_long_date(next_event) %></div>
            <% else %>
              <div class="l-mb--1 pt2">No upcoming events</div>
            <% end %>
            <div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="days-s">00</div>
                <div class="l-blue" id="days-text-s">days</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="hours-s">00</div>
                <div class="l-blue" id="hours-text-s">hours</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="minutes-s">00</div>
                <div class="l-blue" id="minutes-text-s">minutes</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="seconds-s">00</div>
                <div class="l-blue" id="seconds-text-s">seconds</div>
              </div>
            </div>
            <div class="l-lighter-grey pt3">Time until next event</div>
          </td>
        </tr>
      </table>
    </div>
    <div class="pt3 pb4 overflow-scroll l-ns">
      <table class="w-100 data-table">
        <tr>
          <td class="tc pt5 pb5 w-50 data-td">
            <div class="f1"><%= total_fighters %></div>
            <div class="l-lighter-grey">Total fighters</div>
          </td>
          <td class="tc pt5 pb5 w-50 data-td">
            <div class="f1"><%= new_this_month %></div>
            <div class="l-lighter-grey">New this month</div>
          </td>
        </tr>
        <tr>
          <td class="tc pt4 pb4 w-50 data-td overflow-scroll nowrap">
            <div>
              <%= form_for @changeset, event_path(@conn, :create), fn f -> %>
                <%= component "date.html",
                    atom: :date,
                    form: f,
                    label: "" %>
                <div class="tc">
                  <div>
                    <%= submit "Create", class: "white l-b--blue l-bg-blue k-min-h-4-7 ttu pa2 pl4 pr4 f3 br2 lato mt3 no-outline-focus button-active" %>
                  </div>
                </div>
              <% end %>
              <div class="l-lighter-grey pt3">New event</div>
            </div>
          </td>
          <td class="tc pt4 pb4 w-50 data-td">
            <%= if next_event do %>
              <div class="l-mb--1 pt2"><%= format_long_date(next_event) %></div>
            <% else %>
              <div class="l-mb--1 pt2">No upcoming events</div>
            <% end %>
            <div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="days">00</div>
                <div class="l-blue" id="days-text">days</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="hours">00</div>
                <div class="l-blue" id="hours-text">hours</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="minutes">00</div>
                <div class="l-blue" id="minutes-text">minutes</div>
              </div>
              <div class="dib f1 clock-separator">:</div>
              <div class="dib mt4 mb4 l-minw-60">
                <div class="dib f1" id="seconds">00</div>
                <div class="l-blue" id="seconds-text">seconds</div>
              </div>
            </div>
            <div class="l-lighter-grey pt3">Time until next event</div>
          </td>
        </tr>
      </table>
    </div>
    <div class="pt5">Future events</div>
    <%= if length(future_events) == 0 do %>
      <div class="pt3 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Date</th>
            <th align="left" class="nowrap pa4"></th>
          </tr>
        </table>
        <div class="pt4 pb4">
          <div class="f1 tc l-lighter-grey">No upcoming events!</div>
        </div>
      </div>
    <% else %>
      <div class="pt3 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Date</th>
            <th align="left" class="nowrap pa4"></th>
          </tr>
          <%= for {event, index} <- Enum.with_index(future_events) do %>
          <% background_colour =
            case rem(index, 2) == 0 || index == 0 do
              true -> "l-bg-light-blue"
              false -> ""
            end
            %>
          <tr class="data-tr bb <%= background_colour %>">
            <td align="left" class="nowrap pa4"><%= format_long_date(event.date) %></td>
            <td align="right" class="nowrap pa4">
              <%= link to: event_path(@conn, :delete, event), method: :delete do %>
                <img src="/images/cancel.svg" class="w2 pt1" />
              <% end %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
    <% end %>
    <div class="pt5 mb4">Recent sign ups</div>
    <%= if length(@fighters) == 0 do %>
      <div class="pt3 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Name</th>
            <th align="left" class="nowrap pa4">Email</th>
            <th align="left" class="nowrap pa4">Mobile number</th>
            <th align="left" class="nowrap pa4">Occupation</th>
            <th align="left" class="nowrap pa4">Location</th>
            <th align="left" class="nowrap pa4">Signed up</th>
          </tr>
        </table>
        <div class="pt4 pb4">
          <div class="f1 tc l-lighter-grey">No sign ups yet!</div>
        </div>
      </div>
    <% else %>
      <div class="pt3 mb3">
        <%= link "Download CSV", to: csv_path(@conn, :export_fighters), class: "no-underline white l-b--blue l-bg-blue ttu pa3 pl4 pr4 f3 br2 lato mt3 no-outline-focus" %>
      </div>
      <div class="pt4 pb4 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Name</th>
            <th align="left" class="nowrap pa4">Email</th>
            <th align="left" class="nowrap pa4">Mobile number</th>
            <th align="left" class="nowrap pa4">Occupation</th>
            <th align="left" class="nowrap pa4">Location</th>
            <th align="left" class="nowrap pa4">Signed up</th>
          </tr>
          <%= for {fighter, index} <- Enum.reverse(Enum.with_index(@fighters)) do %>
          <% background_colour =
            case rem(index, 2) == 0 || index == 0 do
              true -> "l-bg-light-blue"
              false -> ""
            end
            %>
            <tr class="bb">
              <td class="nowrap pa4 <%= background_colour %>"><%= "#{fighter.title} #{fighter.first_name} #{fighter.last_name}" %></td>
              <td class="nowrap pa4 <%= background_colour %>"><%= fighter.email %></td>
              <td class="nowrap pa4 <%= background_colour %>"><%= fighter.mobile_number %></td>
              <td class="nowrap pa4 <%= background_colour %>"><%= fighter.occupation %></td>
              <td class="nowrap pa4 <%= background_colour %>"><%= fighter.location %></td>
              <td class="nowrap pa4 <%= background_colour %>"><%= get_time(fighter.inserted_at) %></td>
            </tr>
            <% end %>
          </table>
        </div>
    <% end %>
    <div class="pt5">Recent messages</div>
    <%= if length(@contacts) == 0 do %>
      <div class="pt3 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Name</th>
            <th align="left" class="nowrap pa4">Email</th>
            <th align="left" class="nowrap pa4">Mobile number</th>
            <th align="left" class="nowrap pa4">Date</th>
          </tr>
        </table>
        <div class="pt4 pb4">
          <div class="f1 tc l-lighter-grey">No messages yet!</div>
        </div>
      </div>
    <% else %>
      <div class="pt3 pb4 overflow-scroll">
        <table class="w-100 data-table">
          <tr class="data-tr bb">
            <th align="left" class="nowrap pa4">Name</th>
            <th align="left" class="nowrap pa4">Email</th>
            <th align="left" class="nowrap pa4">Mobile number</th>
            <th align="left" class="nowrap pa4">Date</th>
          </tr>
          <%= for {contact, index} <- Enum.with_index(@contacts) do %>
          <% background_colour =
            case rem(index, 2) == 0 || index == 0 do
              true -> "l-bg-light-blue"
              false -> ""
            end
            %>
            <tr class="bb">
              <td class="nowrap pa4 l-bg-light-blue"><%= contact.name %></td>
              <td class="nowrap pa4 l-bg-light-blue"><%= contact.email %></td>
              <td class="nowrap pa4 l-bg-light-blue"><%= contact.mobile_number %></td>
              <td class="nowrap pa4 l-bg-light-blue"><%= get_time(contact.inserted_at) %></td>
            </tr>
            <tr class="bb">
              <td class="l-minw-30 pa4"><%= contact.message %></td>
              <td class="nowrap pa4"></td>
              <td class="nowrap pa4"></td>
              <td class="nowrap pa4"></td>
            </tr>
            <% end %>
          </table>
        </div>
    <% end %>
  </div>
</div>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<%= if next_event do %>
  <script>require("js/app").App.timerListeners(<%= next_event.day %>, <%= next_event.month %>, <%= next_event.year %>, "")</script>
  <script>require("js/app").App.timerListeners(<%= next_event.day %>, <%= next_event.month %>, <%= next_event.year %>, "-s")</script>
<% end %>