lib/lfc_web/router.ex
defmodule LfcWeb.Router do
  use LfcWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LfcWeb.Auth, accounts: Lfc.Accounts

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", DashboardController, only: [:index]
    resources "/users", UserController, except: [:delete]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/password", PasswordController, except: [:delete, :show, :index]
    get "/verification/:hash", VerificationController, :verify
    get "/verification/verify/:hash", VerificationController, :verify_again
    get "/verification/resend/:hash", VerificationController, :resend
    get "/sign-up", FighterController, :new
    get "/thank-you", FighterController, :thank_you
    resources "/sign-up", FighterController, only: [:create]
    resources "/contacts", ContactController, only: [:create]
  end

  # authed routes
  scope "/", LfcWeb do
    pipe_through [:browser, :authenticate]

    resources "/dashboard", AdminDashboardController, only: [:index]
    resources "/events", EventController, only: [:create, :delete]
    get "/fighter-csv", CsvController, :export_fighters
  end

  # Other scopes may use custom stacks.
  # scope "/api", LfcWeb do
  #   pipe_through :api
  # end
end

lib/lfc_web/controllers/session_controller.ex
defmodule LfcWeb.SessionController do
  @moduledoc """
  Session Controller
  """
  use LfcWeb, :controller

  alias Lfc.{Accounts, Accounts.User}
  alias LfcWeb.{Auth, LayoutView}

  def new(conn, _params) do
    case conn.assigns.current_user do
      nil ->
        changeset = User.changeset(%User{})
        render(
          conn,
          "new.html",
          layout: {LayoutView, "pre_login.html"},
          changeset: changeset
        )
      _user ->
        conn
        |> put_flash(:info, "You are already logged in!")
        |> redirect(to: dashboard_path(conn, :index))
    end
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    case Auth.login_by_email_and_pass(conn, email, pass, accounts: Accounts) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: admin_dashboard_path(conn, :index))
      {:error, :unauthorized, conn} ->
        conn
        |> put_flash(:error, "Invalid email/password combination")
        |> redirect(to: session_path(conn, :new))
      {:error, :not_verified, conn} ->
        rand_string = Accounts.set_as_key_and_value(email)
        conn
        |> put_flash(:error, "Your email address is yet to be verified")
        |> redirect(to: verification_path(conn, :verify_again, rand_string))
    end
  end

  def delete(conn, _) do
    conn
    |> Auth.logout()
    |> redirect(to: session_path(conn, :new))
  end

end

lib/lfc_web/views/session_view.ex
defmodule LfcWeb.SessionView do
  use LfcWeb, :view
end

lib/lfc_web/templates/session/new.html.eex
<div class="vh-100 w-100 mw7-ns center dt roboto white">
  <div class="dtc v-mid">
    <div class="ba b--black-10 br4 pa4 bg-white h-auto-ns h-100 l-bg-dark-grey">
      <div class="tc mt4">
        <div class="f2">Fight Club London</div>
      </div>
      <div class="mt5">
        <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>

          <%= component "input.html",
          form: f,
          image_name: "user",
          atom: :email,
          autofill: "on",
          placeholder: "example@email.com"
          %>
          <%= component "input.html",
          form: f,
          image_name: "locked",
          atom: :password,
          type: :password,
          autofill: "on",
          placeholder: "Minimum 6 characters"
          %>

          <div class="tc">
            <div class="mb4">
              <%= submit "Sign in", class: "white l-b--blue l-bg-blue k-min-h-4-7 ttu pa3 pl4 pr4 k-f2-5 br2 w-100 lato mt3 no-outline-focus button-active" %>
            </div>
          </div>
          <div class="pa4 tc">
            <%= link "Forgot / reset password", to: password_path(@conn, :new), class: "white underline" %>
            <%= component "divider.html" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>